module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./src/screens/**/*.{js,ts,jsx,tsx}",
    "./src/navigators/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    fontSize: {
      size_8: 8,
      size_10: 10,
      size_12: 12,
      size_14: 14,
      size_16: 16,
      size_18: 18,
      size_20: 20,
      size_24: 24,
      size_30: 30,
    },
    extend: {
      fontFamily: {
        Poppins_Black: ["Poppins_Black"],
        Poppins_BlackItalic: ["Poppins_BlackItalic"],
        Poppins_Bold: ["Poppins_Bold"],
        Poppins_BoldItalic: ["Poppins_BoldItalic"],
        Poppins_ExtraBold: ["Poppins_ExtraBold"],
        Poppins_ExtraBoldItalic: ["Poppins_ExtraBoldItalic"],
        Poppins_ExtraLight: ["Poppins_ExtraLight"],
        Poppins_ExtraLightItalic: ["Poppins_ExtraLightItalic"],
        Poppins_Italic: ["Poppins_Italic"],
        Poppins_Light: ["Poppins_Light"],
        Poppins_LightItalic: ["Poppins_LightItalic"],
        Poppins_Medium: ["Poppins_Medium"],
        Poppins_MediumItalic: ["Poppins_MediumItalic"],
        Poppins_Regular: ["Poppins_Regular"],
        Poppins_SemiBold: ["Poppins_SemiBold"],
        Poppins_Thin: ["Poppins_Thin"],
        Poppins_ThinItalic: ["Poppins_ThinItalic"],
      },
      colors: {
        Green: "#6BD425",
        GreenRGBA0: "rgba(107,212,37,0)",
        Black: "#000000",
        BlackRGB10: "rgba(0,0,0,0.1)",
        Orange: "#FF5524",
        OrangeRGBA0: "rgba(255,85,36,0)",
        Grey: "#333333",
        DarkGrey: "#0b0b0b",
        Yellow: "#E1CD17",
        White: "#FFFFFF",
        WhiteRGBA75: "rgba(255,255,255,0.75)",
        WhiteRGBA50: "rgba(255,255,255,0.50)",
        WhiteRGBA32: "rgba(255,255,255,0.32)",
        WhiteRGBA15: "rgba(255,255,255,0.15)",
      },
      spacing: {
        space_2: 2,
        space_4: 4,
        space_8: 8,
        space_10: 10,
        space_12: 12,
        space_15: 15,
        space_16: 16,
        space_18: 18,
        space_20: 20,
        space_24: 24,
        space_28: 28,
        space_32: 32,
        space_36: 36,
      },
    },
  },
  plugins: [],
};
